
export interface Location {
  value: string;
  label: string;
  region: 'trinidad' | 'tobago';
  administrative_region: string;
}

export const TRINIDAD_TOBAGO_LOCATIONS: Location[] = [
  // Trinidad locations
  { value: 'aranguez', label: 'San Juan–Laventille - Aranguez', region: 'trinidad', administrative_region: 'San Juan–Laventille' },
  { value: 'arima', label: 'Borough of Arima - Arima', region: 'trinidad', administrative_region: 'Borough of Arima' },
  { value: 'arena', label: 'Couva-Tabaquite-Talparo - Arena', region: 'trinidad', administrative_region: 'Couva-Tabaquite-Talparo' },
  { value: 'arouca', label: 'Tunapuna–Piarco - Arouca', region: 'trinidad', administrative_region: 'Tunapuna–Piarco' },
  { value: 'arquart_village', label: 'Penal–Debe - Arquart Village', region: 'trinidad', administrative_region: 'Penal–Debe' },
  { value: 'auzonville', label: 'Tunapuna–Piarco - Auzonville', region: 'trinidad', administrative_region: 'Tunapuna–Piarco' },
  { value: 'avocat', label: 'Siparia - Avocat', region: 'trinidad', administrative_region: 'Siparia' },
  { value: 'balmain', label: 'Couva–Tabaquite–Talparo - Balmain', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'bamboo_no_1_3', label: 'San Juan–Laventille - Bamboo (No. 1 & No. 3)', region: 'trinidad', administrative_region: 'San Juan–Laventille' },
  { value: 'bamboo_no_2', label: 'Tunapuna–Piarco - Bamboo No. 2', region: 'trinidad', administrative_region: 'Tunapuna–Piarco' },
  { value: 'bangladesh', label: 'Tunapuna–Piarco - Bangladesh', region: 'trinidad', administrative_region: 'Tunapuna–Piarco' },
  { value: 'barataria', label: 'San Juan–Laventille - Barataria', region: 'trinidad', administrative_region: 'San Juan–Laventille' },
  { value: 'barrackpore', label: 'Penal–Debe - Barrackpore', region: 'trinidad', administrative_region: 'Penal–Debe' },
  { value: 'basta_hall', label: 'Couva–Tabaquite–Talparo - Basta Hall', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'beetham_estate_gardens', label: 'Port of Spain - Beetham Estate Gardens', region: 'trinidad', administrative_region: 'Port of Spain' },
  { value: 'belmont', label: 'Port of Spain - Belmont', region: 'trinidad', administrative_region: 'Port of Spain' },
  { value: 'ben_lomond', label: 'Couva–Tabaquite–Talparo - Ben Lomond', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'biche', label: 'Rio Claro–Mayaro - Biche', region: 'trinidad', administrative_region: 'Rio Claro–Mayaro' },
  { value: 'blanchisseuse', label: 'Tunapuna–Piarco - Blanchisseuse', region: 'trinidad', administrative_region: 'Tunapuna–Piarco' },
  { value: 'boissiere_village', label: 'Diego Martin - Boissiere Village', region: 'trinidad', administrative_region: 'Diego Martin' },
  { value: 'bonasse', label: 'Siparia - Bonasse', region: 'trinidad', administrative_region: 'Siparia' },
  { value: 'bonne_aventure', label: 'Couva–Tabaquite–Talparo - Bonne Aventure', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'borde_narve_village', label: 'Princes Town - Borde Narve Village', region: 'trinidad', administrative_region: 'Princes Town' },
  { value: 'bourg_mulatresse', label: 'San Juan–Laventille - Bourg Mulatresse', region: 'trinidad', administrative_region: 'San Juan–Laventille' },
  { value: 'brasso', label: 'Couva–Tabaquite–Talparo - Brasso', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'brasso_seco', label: 'Tunapuna–Piarco - Brasso Seco', region: 'trinidad', administrative_region: 'Tunapuna–Piarco' },
  { value: 'brazil', label: 'Couva–Tabaquite–Talparo - Brazil', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'brickfield', label: 'Couva–Tabaquite–Talparo - Brickfield', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'brighton', label: 'Siparia - Brighton', region: 'trinidad', administrative_region: 'Siparia' },
  { value: 'buen_intento_village', label: 'Princes Town - Buen Intento Village', region: 'trinidad', administrative_region: 'Princes Town' },
  { value: 'buenos_ayres', label: 'Siparia - Buenos Ayres', region: 'trinidad', administrative_region: 'Siparia' },
  { value: 'caigual', label: 'Sangre Grande - Caigual', region: 'trinidad', administrative_region: 'Sangre Grande' },
  { value: 'calcutta_settlement', label: 'Couva–Tabaquite–Talparo - Calcutta Settlement', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'california', label: 'Couva–Tabaquite–Talparo - California', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'canaan_trinidad', label: 'Penal-Debe - Canaan', region: 'trinidad', administrative_region: 'Penal-Debe' },
  { value: 'cantaro', label: 'San Juan-Laventille - Cantaro', region: 'trinidad', administrative_region: 'San Juan-Laventille' },
  { value: 'carapichaima', label: 'Couva–Tabaquite–Talparo - Carapichaima', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'carenage', label: 'Diego Martin - Carenage', region: 'trinidad', administrative_region: 'Diego Martin' },
  { value: 'carli_bay', label: 'Couva–Tabaquite–Talparo - Carli Bay', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'carlsen_field', label: 'Couva–Tabaquite–Talparo - Carlsen Field', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'cascade', label: 'San Juan-Laventille - Cascade', region: 'trinidad', administrative_region: 'San Juan-Laventille' },
  { value: 'caura', label: 'Tunapuna-Piarco - Caura', region: 'trinidad', administrative_region: 'Tunapuna-Piarco' },
  { value: 'cedar_hill_village', label: 'Princes Town - Cedar Hill Village', region: 'trinidad', administrative_region: 'Princes Town' },
  { value: 'cedros', label: 'Siparia - Cedros', region: 'trinidad', administrative_region: 'Siparia' },
  { value: 'centeno', label: 'Tunapuna-Piarco - Centeno', region: 'trinidad', administrative_region: 'Tunapuna-Piarco' },
  { value: 'chaguanas', label: 'Borough of Chaguanas - Chaguanas', region: 'trinidad', administrative_region: 'Borough of Chaguanas' },
  { value: 'chaguaramas', label: 'Diego Martin - Chaguaramas', region: 'trinidad', administrative_region: 'Diego Martin' },
  { value: 'champs_fleurs', label: 'San Juan–Laventille - Champs Fleurs', region: 'trinidad', administrative_region: 'San Juan–Laventille' },
  { value: 'chandernagore_village', label: 'Couva–Tabaquite–Talparo - Chandernagore Village', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'charuma', label: 'Mayaro-Rio Claro - Charuma', region: 'trinidad', administrative_region: 'Mayaro-Rio Claro' },
  { value: 'chase_village', label: 'Couva–Tabaquite–Talparo - Chase Village', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'chatham', label: 'Siparia - Chatham', region: 'trinidad', administrative_region: 'Siparia' },
  { value: 'churkoo_village', label: 'Princes Town - Churkoo Village', region: 'trinidad', administrative_region: 'Princes Town' },
  { value: 'claxton_bay', label: 'Couva–Tabaquite–Talparo - Claxton Bay', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'cocorite', label: 'Diego Martin - Cocorite', region: 'trinidad', administrative_region: 'Diego Martin' },
  { value: 'cocoyea_village', label: 'City of San Fernando - Cocoyea Village', region: 'trinidad', administrative_region: 'City of San Fernando' },
  { value: 'congo_village', label: 'Penal–Debe - Congo Village', region: 'trinidad', administrative_region: 'Penal–Debe' },
  { value: 'coryal', label: 'Sangre Grande - Coryal', region: 'trinidad', administrative_region: 'Sangre Grande' },
  { value: 'couva', label: 'Couva–Tabaquite–Talparo - Couva', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'cumaca', label: 'Sangre Grande - Cumaca', region: 'trinidad', administrative_region: 'Sangre Grande' },
  { value: 'cumuto', label: 'Sangre Grande - Cumuto', region: 'trinidad', administrative_region: 'Sangre Grande' },
  { value: 'cunupia', label: 'Borough of Chaguanas - Cunupia', region: 'trinidad', administrative_region: 'Borough of Chaguanas' },
  { value: 'curepe', label: 'Tunapuna–Piarco - Curepe', region: 'trinidad', administrative_region: 'Tunapuna–Piarco' },
  { value: 'cushe', label: 'Mayaro-Rio Claro - Cushe', region: 'trinidad', administrative_region: 'Mayaro-Rio Claro' },
  { value: 'dabadie', label: 'Tunapuna–Piarco - D\'Abadie', region: 'trinidad', administrative_region: 'Tunapuna–Piarco' },
  { value: 'datsunville', label: 'Borough of Chaguanas - Datsunville', region: 'trinidad', administrative_region: 'Borough of Chaguanas' },
  { value: 'debe', label: 'Penal–Debe - Debe', region: 'trinidad', administrative_region: 'Penal–Debe' },
  { value: 'diamond_village', label: 'Penal–Debe - Diamond Village', region: 'trinidad', administrative_region: 'Penal–Debe' },
  { value: 'dibe', label: 'Diego Martin - Dibe', region: 'trinidad', administrative_region: 'Diego Martin' },
  { value: 'diego_martin', label: 'Diego Martin - Diego Martin', region: 'trinidad', administrative_region: 'Diego Martin' },
  { value: 'dinsley', label: 'Tunapuna–Piarco - Dinsley', region: 'trinidad', administrative_region: 'Tunapuna–Piarco' },
  { value: 'dow_village_couva', label: 'Couva–Tabaquite–Talparo - Dow Village', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'dow_village_siparia', label: 'Siparia - Dow Village', region: 'trinidad', administrative_region: 'Siparia' },
  { value: 'duncan_village', label: 'Penal–Debe - Duncan Village', region: 'trinidad', administrative_region: 'Penal–Debe' },
  { value: 'ecclesville', label: 'Rio Claro–Mayaro - Ecclesville', region: 'trinidad', administrative_region: 'Rio Claro–Mayaro' },
  { value: 'eckel_village', label: 'Couva–Tabaquite–Talparo - Eckel Village', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'edinburgh', label: 'Borough of Chaguanas - Edinburgh', region: 'trinidad', administrative_region: 'Borough of Chaguanas' },
  { value: 'el_dorado', label: 'Tunapuna–Piarco - El Dorado', region: 'trinidad', administrative_region: 'Tunapuna–Piarco' },
  { value: 'el_socorro', label: 'Tunapuna–Piarco - El Socorro', region: 'trinidad', administrative_region: 'Tunapuna–Piarco' },
  { value: 'enterprise', label: 'Borough of Chaguanas - Enterprise', region: 'trinidad', administrative_region: 'Borough of Chaguanas' },
  { value: 'endeavour', label: 'Borough of Chaguanas - Endeavour', region: 'trinidad', administrative_region: 'Borough of Chaguanas' },
  { value: 'erin', label: 'Siparia - Erin', region: 'trinidad', administrative_region: 'Siparia' },
  { value: 'exchange', label: 'Couva–Tabaquite–Talparo - Exchange', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'febeau_village', label: 'San Juan–Laventille - Febeau Village', region: 'trinidad', administrative_region: 'San Juan–Laventille' },
  { value: 'felicity', label: 'Borough of Chaguanas - Felicity', region: 'trinidad', administrative_region: 'Borough of Chaguanas' },
  { value: 'fifth_company', label: 'Princes Town - Fifth Company', region: 'trinidad', administrative_region: 'Princes Town' },
  { value: 'fishing_pond', label: 'Sangre Grande - Fishing Pond', region: 'trinidad', administrative_region: 'Sangre Grande' },
  { value: 'flanigin_town', label: 'Couva–Tabaquite–Talparo - Flanigin Town', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'freeport', label: 'Couva–Tabaquite–Talparo - Freeport', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'forres_park', label: 'Couva–Tabaquite–Talparo - Forres Park', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'four_roads', label: 'Diego Martin - Four Roads', region: 'trinidad', administrative_region: 'Diego Martin' },
  { value: 'frederick_settlement', label: 'Tunapuna–Piarco - Frederick Settlement', region: 'trinidad', administrative_region: 'Tunapuna–Piarco' },
  { value: 'friendship_village', label: 'Princes Town - Friendship Village', region: 'trinidad', administrative_region: 'Princes Town' },
  { value: 'fullarton', label: 'Siparia - Fullarton', region: 'trinidad', administrative_region: 'Siparia' },
  { value: 'fyzabad', label: 'Siparia - Fyzabad', region: 'trinidad', administrative_region: 'Siparia' },
  { value: 'gasparillo', label: 'Couva–Tabaquite–Talparo - Gasparillo', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'glencoe', label: 'Diego Martin - Glencoe', region: 'trinidad', administrative_region: 'Diego Martin' },
  { value: 'golconda', label: 'Princes Town - Golconda', region: 'trinidad', administrative_region: 'Princes Town' },
  { value: 'gonzales', label: 'San Juan–Laventille - Gonzales', region: 'trinidad', administrative_region: 'San Juan–Laventille' },
  { value: 'gopaul_lands', label: 'San Fernando - Gopaul Lands', region: 'trinidad', administrative_region: 'San Fernando' },
  { value: 'goodwood_park', label: 'Diego Martin - Goodwood Park', region: 'trinidad', administrative_region: 'Diego Martin' },
  { value: 'gran_couva', label: 'Couva–Tabaquite–Talparo - Gran Couva', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'grande_riviere', label: 'Sangre Grande - Grande Riviere', region: 'trinidad', administrative_region: 'Sangre Grande' },
  { value: 'guaico', label: 'Sangre Grande - Guaico', region: 'trinidad', administrative_region: 'Sangre Grande' },
  { value: 'guanapo', label: 'Sangre Grande - Guanapo', region: 'trinidad', administrative_region: 'Sangre Grande' },
  { value: 'guapo', label: 'Borough of Point Fortin - Guapo', region: 'trinidad', administrative_region: 'Borough of Point Fortin' },
  { value: 'guayaguayare', label: 'Rio Claro–Mayaro - Guayaguayare', region: 'trinidad', administrative_region: 'Rio Claro–Mayaro' },
  { value: 'gulf_view', label: 'City of San Fernando - Gulf View', region: 'trinidad', administrative_region: 'City of San Fernando' },
  { value: 'hardbargain', label: 'Princes Town - Hardbargain', region: 'trinidad', administrative_region: 'Princes Town' },
  { value: 'hindustan', label: 'Princes Town - Hindustan', region: 'trinidad', administrative_region: 'Princes Town' },
  { value: 'icacos', label: 'Siparia - Icacos', region: 'trinidad', administrative_region: 'Siparia' },
  { value: 'iere_village', label: 'Princes Town - Iere Village', region: 'trinidad', administrative_region: 'Princes Town' },
  { value: 'indian_chain', label: 'Couva-Tabaquite-Talparo - Indian Chain', region: 'trinidad', administrative_region: 'Couva-Tabaquite-Talparo' },
  { value: 'indian_walk', label: 'Princes Town - Indian Walk', region: 'trinidad', administrative_region: 'Princes Town' },
  { value: 'jerningham_junction', label: 'Borough of Chaguanas - Jerningham Junction', region: 'trinidad', administrative_region: 'Borough of Chaguanas' },
  { value: 'john_john', label: 'City of Port of Spain - John John', region: 'trinidad', administrative_region: 'City of Port of Spain' },
  { value: 'jordan_hill', label: 'Princes Town - Jordan Hill', region: 'trinidad', administrative_region: 'Princes Town' },
  { value: 'kelly_village', label: 'Tunapuna–Piarco - Kelly Village', region: 'trinidad', administrative_region: 'Tunapuna–Piarco' },
  { value: 'kernaham', label: 'Rio Claro–Mayaro - Kernaham', region: 'trinidad', administrative_region: 'Rio Claro–Mayaro' },
  { value: 'kumar_village', label: 'Princes Town - Kumar Village', region: 'trinidad', administrative_region: 'Princes Town' },
  { value: 'lanse_mitan', label: 'Diego Martin - L\'Anse Mitan', region: 'trinidad', administrative_region: 'Diego Martin' },
  { value: 'la_brea', label: 'Siparia - La Brea', region: 'trinidad', administrative_region: 'Siparia' },
  { value: 'la_canoa', label: 'San Juan–Laventille - La Canoa', region: 'trinidad', administrative_region: 'San Juan–Laventille' },
  { value: 'la_horquetta', label: 'Tunapuna–Piarco - La Horquetta', region: 'trinidad', administrative_region: 'Tunapuna–Piarco' },
  { value: 'la_paille', label: 'Tunapuna-Piarco - La Paille', region: 'trinidad', administrative_region: 'Tunapuna-Piarco' },
  { value: 'la_romaine', label: 'City of San Fernando - La Romaine', region: 'trinidad', administrative_region: 'City of San Fernando' },
  { value: 'las_lomas', label: 'Tunapuna–Piarco - Las Lomas', region: 'trinidad', administrative_region: 'Tunapuna–Piarco' },
  { value: 'las_cuevas', label: 'San Juan–Laventille - Las Cuevas', region: 'trinidad', administrative_region: 'San Juan–Laventille' },
  { value: 'laventille', label: 'San Juan–Laventille - Laventille', region: 'trinidad', administrative_region: 'San Juan–Laventille' },
  { value: 'lengua', label: 'Princes Town - Lengua', region: 'trinidad', administrative_region: 'Princes Town' },
  { value: 'longdenville', label: 'Borough of Chaguanas - Longdenville', region: 'trinidad', administrative_region: 'Borough of Chaguanas' },
  { value: 'lopinot', label: 'Tunapuna–Piarco - Lopinot', region: 'trinidad', administrative_region: 'Tunapuna–Piarco' },
  { value: 'los_bajos', label: 'Siparia - Los Bajos', region: 'trinidad', administrative_region: 'Siparia' },
  { value: 'macoya', label: 'Tunapuna–Piarco - Macoya', region: 'trinidad', administrative_region: 'Tunapuna–Piarco' },
  { value: 'madras_settlement', label: 'Couva-Tabaquite-Talparo - Madras Settlement', region: 'trinidad', administrative_region: 'Couva-Tabaquite-Talparo' },
  { value: 'mairao_village', label: 'Rio Claro–Mayaro - Mairao Village', region: 'trinidad', administrative_region: 'Rio Claro–Mayaro' },
  { value: 'malabar', label: 'Borough of Arima - Malabar', region: 'trinidad', administrative_region: 'Borough of Arima' },
  { value: 'malick', label: 'San Juan–Laventille - Malick', region: 'trinidad', administrative_region: 'San Juan–Laventille' },
  { value: 'manzanilla', label: 'Sangre Grande - Manzanilla', region: 'trinidad', administrative_region: 'Sangre Grande' },
  { value: 'marabella', label: 'City of San Fernando - Marabella', region: 'trinidad', administrative_region: 'City of San Fernando' },
  { value: 'maracas', label: 'San Juan–Laventille - Maracas', region: 'trinidad', administrative_region: 'San Juan–Laventille' },
  { value: 'maraval', label: 'Diego Martin - Maraval', region: 'trinidad', administrative_region: 'Diego Martin' },
  { value: 'matelot', label: 'Sangre Grande - Matelot', region: 'trinidad', administrative_region: 'Sangre Grande' },
  { value: 'matura', label: 'Sangre Grande - Matura', region: 'trinidad', administrative_region: 'Sangre Grande' },
  { value: 'mausica', label: 'Tunapuna-Piarco - Mausica', region: 'trinidad', administrative_region: 'Tunapuna-Piarco' },
  { value: 'mayaro', label: 'Rio Claro–Mayaro - Mayaro', region: 'trinidad', administrative_region: 'Rio Claro–Mayaro' },
  { value: 'mayo', label: 'Couva–Tabaquite–Talparo - Mayo', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'mc_bean', label: 'Couva–Tabaquite–Talparo - Mc Bean', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'mohammedville', label: 'San Juan–Laventille - Mohammedville', region: 'trinidad', administrative_region: 'San Juan–Laventille' },
  { value: 'mon_repos', label: 'City of San Fernando - Mon Repos', region: 'trinidad', administrative_region: 'City of San Fernando' },
  { value: 'montrose', label: 'Borough of Chaguanas - Montrose', region: 'trinidad', administrative_region: 'Borough of Chaguanas' },
  { value: 'monkey_town', label: 'Penal-Debe - Monkey Town', region: 'trinidad', administrative_region: 'Penal-Debe' },
  { value: 'montserrat', label: 'Couva–Tabaquite–Talparo - Montserrat', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'morang', label: 'Tunapuna-Piarco - Morang', region: 'trinidad', administrative_region: 'Tunapuna-Piarco' },
  { value: 'morne_diablo', label: 'Penal–Debe - Morne Diablo', region: 'trinidad', administrative_region: 'Penal–Debe' },
  { value: 'moruga', label: 'Princes Town - Moruga', region: 'trinidad', administrative_region: 'Princes Town' },
  { value: 'morvant', label: 'San Juan–Laventille - Morvant', region: 'trinidad', administrative_region: 'San Juan–Laventille' },
  { value: 'mount_dor', label: 'San Juan-Laventille - Mount D\'Or', region: 'trinidad', administrative_region: 'San Juan-Laventille' },
  { value: 'mount_lambert', label: 'San Juan-Laventille - Mount Lambert', region: 'trinidad', administrative_region: 'San Juan-Laventille' },
  { value: 'mount_stewart', label: 'Princes Town - Mount Stewart', region: 'trinidad', administrative_region: 'Princes Town' },
  { value: 'mucurapo', label: 'City of Port of Spain - Mucurapo', region: 'trinidad', administrative_region: 'City of Port of Spain' },
  { value: 'navet', label: 'Couva–Tabaquite–Talparo - Navet', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'new_grant', label: 'Princes Town - New Grant', region: 'trinidad', administrative_region: 'Princes Town' },
  { value: 'omeara', label: 'Borough of Arima - O\'Meara', region: 'trinidad', administrative_region: 'Borough of Arima' },
  { value: 'orange_valley', label: 'Couva–Tabaquite–Talparo - Orange Valley', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'oropune_village', label: 'Tunapuna–Piarco - Oropune Village', region: 'trinidad', administrative_region: 'Tunapuna–Piarco' },
  { value: 'oropouche', label: 'Siparia - Oropouche', region: 'trinidad', administrative_region: 'Siparia' },
  { value: 'ortoire', label: 'Mayaro–Rio Claro - Ortoire', region: 'trinidad', administrative_region: 'Mayaro–Rio Claro' },
  { value: 'otaheite', label: 'Siparia - Otaheite', region: 'trinidad', administrative_region: 'Siparia' },
  { value: 'palmyra', label: 'Princes Town - Palmyra', region: 'trinidad', administrative_region: 'Princes Town' },
  { value: 'palo_seco', label: 'Siparia - Palo Seco', region: 'trinidad', administrative_region: 'Siparia' },
  { value: 'patna_village', label: 'Diego Martin - Patna Village', region: 'trinidad', administrative_region: 'Diego Martin' },
  { value: 'penal', label: 'Penal–Debe - Penal', region: 'trinidad', administrative_region: 'Penal–Debe' },
  { value: 'penal_rock', label: 'Princes Town - Penal Rock', region: 'trinidad', administrative_region: 'Princes Town' },
  { value: 'petit_trou', label: 'Sangre Grande - Petit Trou', region: 'trinidad', administrative_region: 'Sangre Grande' },
  { value: 'petit_valley', label: 'Diego Martin - Petit Valley', region: 'trinidad', administrative_region: 'Diego Martin' },
  { value: 'phoenix_park', label: 'Couva–Tabaquite–Talparo - Phoenix Park', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'piarco', label: 'Tunapuna–Piarco - Piarco', region: 'trinidad', administrative_region: 'Tunapuna–Piarco' },
  { value: 'pierreville', label: 'Rio Claro–Mayaro - Pierreville', region: 'trinidad', administrative_region: 'Rio Claro–Mayaro' },
  { value: 'piparo', label: 'Couva–Tabaquite–Talparo - Piparo', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'plaisance', label: 'Rio Claro–Mayaro - Plaisance', region: 'trinidad', administrative_region: 'Rio Claro–Mayaro' },
  { value: 'plaisance_park', label: 'Couva–Tabaquite–Talparo - Plaisance Park', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'point_fortin', label: 'Borough of Point Fortin - Point Fortin', region: 'trinidad', administrative_region: 'Borough of Point Fortin' },
  { value: 'point_lisas', label: 'Couva–Tabaquite–Talparo - Point Lisas', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'pointe_a_pierre', label: 'Couva–Tabaquite–Talparo - Pointe-à-Pierre', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'poole', label: 'Mayaro-Rio Claro - Poole', region: 'trinidad', administrative_region: 'Mayaro-Rio Claro' },
  { value: 'port_of_spain', label: 'City of Port of Spain - Port of Spain', region: 'trinidad', administrative_region: 'City of Port of Spain' },
  { value: 'preysal', label: 'Couva–Tabaquite–Talparo - Preysal', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'princes_town', label: 'Princes Town - Princes Town', region: 'trinidad', administrative_region: 'Princes Town' },
  { value: 'quarry_village', label: 'Siparia - Quarry Village', region: 'trinidad', administrative_region: 'Siparia' },
  { value: 'quinam', label: 'Siparia - Quinam', region: 'trinidad', administrative_region: 'Siparia' },
  { value: 'rampanalgas', label: 'Sangre Grande - Rampanalgas', region: 'trinidad', administrative_region: 'Sangre Grande' },
  { value: 'rancho_quemado', label: 'Siparia - Rancho Quemado', region: 'trinidad', administrative_region: 'Siparia' },
  { value: 'ravin_anglais', label: 'Sangre Grande - Ravin Anglais', region: 'trinidad', administrative_region: 'Sangre Grande' },
  { value: 'redhead', label: 'Sangre Grande - Redhead', region: 'trinidad', administrative_region: 'Sangre Grande' },
  { value: 'rio_claro', label: 'Rio Claro–Mayaro - Rio Claro', region: 'trinidad', administrative_region: 'Rio Claro–Mayaro' },
  { value: 'roussillac', label: 'Siparia - Roussillac', region: 'trinidad', administrative_region: 'Siparia' },
  { value: 'st_anns', label: 'San Juan-Laventille - St. Ann\'s', region: 'trinidad', administrative_region: 'San Juan-Laventille' },
  { value: 'st_augustine', label: 'Tunapuna–Piarco - St. Augustine', region: 'trinidad', administrative_region: 'Tunapuna–Piarco' },
  { value: 'st_barbs', label: 'San Juan-Laventille - St. Barb\'s', region: 'trinidad', administrative_region: 'San Juan-Laventille' },
  { value: 'st_clair', label: 'Port of Spain - St. Clair', region: 'trinidad', administrative_region: 'Port of Spain' },
  { value: 'st_helena', label: 'Tunapuna-Piarco - St. Helena', region: 'trinidad', administrative_region: 'Tunapuna-Piarco' },
  { value: 'st_james', label: 'Port of Spain - St. James', region: 'trinidad', administrative_region: 'Port of Spain' },
  { value: 'st_joseph', label: 'Tunapuna–Piarco - St. Joseph', region: 'trinidad', administrative_region: 'Tunapuna–Piarco' },
  { value: 'st_marys', label: 'Couva–Tabaquite–Talparo - St. Mary\'s', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'saint_madeleine', label: 'Princes Town - Saint Madeleine', region: 'trinidad', administrative_region: 'Princes Town' },
  { value: 'san_fernando', label: 'City of San Fernando - San Fernando', region: 'trinidad', administrative_region: 'City of San Fernando' },
  { value: 'san_francique', label: 'Penal-Debe - San Francique', region: 'trinidad', administrative_region: 'Penal-Debe' },
  { value: 'san_juan', label: 'San Juan–Laventille - San Juan', region: 'trinidad', administrative_region: 'San Juan–Laventille' },
  { value: 'san_raphael', label: 'Couva-Tabaquite-Talparo - San Raphael', region: 'trinidad', administrative_region: 'Couva-Tabaquite-Talparo' },
  { value: 'sans_souci', label: 'Sangre Grande - Sans Souci', region: 'trinidad', administrative_region: 'Sangre Grande' },
  { value: 'sangre_chiquito', label: 'Sangre Grande - Sangre Chiquito', region: 'trinidad', administrative_region: 'Sangre Grande' },
  { value: 'sangre_grande', label: 'Sangre Grande - Sangre Grande', region: 'trinidad', administrative_region: 'Sangre Grande' },
  { value: 'santa_cruz', label: 'San Juan–Laventille - Santa Cruz', region: 'trinidad', administrative_region: 'San Juan–Laventille' },
  { value: 'santa_flora', label: 'Siparia - Santa Flora', region: 'trinidad', administrative_region: 'Siparia' },
  { value: 'santa_margarita', label: 'Tunapuna–Piarco - Santa Margarita', region: 'trinidad', administrative_region: 'Tunapuna–Piarco' },
  { value: 'santa_rosa', label: 'Arima - Santa Rosa', region: 'trinidad', administrative_region: 'Arima' },
  { value: 'savonetta', label: 'Couva–Tabaquite–Talparo - Savonetta', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'siparia', label: 'Siparia - Siparia', region: 'trinidad', administrative_region: 'Siparia' },
  { value: 'south_oropouche', label: 'Siparia - South Oropouche', region: 'trinidad', administrative_region: 'Siparia' },
  { value: 'spring_village', label: 'Tunapuna-Piarco - Spring Village', region: 'trinidad', administrative_region: 'Tunapuna-Piarco' },
  { value: 'syne_village', label: 'Siparia - Syne Village', region: 'trinidad', administrative_region: 'Siparia' },
  { value: 'tabaquite', label: 'Couva–Tabaquite–Talparo - Tabaquite', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'tacarigua', label: 'Tunapuna–Piarco - Tacarigua', region: 'trinidad', administrative_region: 'Tunapuna–Piarco' },
  { value: 'talparo', label: 'Couva–Tabaquite–Talparo - Talparo', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'techier_village', label: 'Point Fortin - Techier Village', region: 'trinidad', administrative_region: 'Point Fortin' },
  { value: 'thick_village', label: 'Siparia - Thick Village', region: 'trinidad', administrative_region: 'Siparia' },
  { value: 'third_company', label: 'Princes Town - Third Company', region: 'trinidad', administrative_region: 'Princes Town' },
  { value: 'toco', label: 'Sangre Grande - Toco', region: 'trinidad', administrative_region: 'Sangre Grande' },
  { value: 'tortuga', label: 'Couva–Tabaquite–Talparo - Tortuga', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'trincity', label: 'Tunapuna–Piarco - Trincity', region: 'trinidad', administrative_region: 'Tunapuna–Piarco' },
  { value: 'trou_macaque', label: 'San Juan-Laventille - Trou Macaque', region: 'trinidad', administrative_region: 'San Juan-Laventille' },
  { value: 'tunapuna', label: 'Tunapuna–Piarco - Tunapuna', region: 'trinidad', administrative_region: 'Tunapuna–Piarco' },
  { value: 'tableland', label: 'Princes Town - Tableland', region: 'trinidad', administrative_region: 'Princes Town' },
  { value: 'union_village', label: 'Couva–Tabaquite–Talparo - Union Village', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'valencia', label: 'Sangre Grande - Valencia', region: 'trinidad', administrative_region: 'Sangre Grande' },
  { value: 'valsayn', label: 'Tunapuna–Piarco - Valsayn', region: 'trinidad', administrative_region: 'Tunapuna–Piarco' },
  { value: 'vega_de_oropouche', label: 'Sangre Grande - Vega de Oropouche', region: 'trinidad', administrative_region: 'Sangre Grande' },
  { value: 'vessigny', label: 'Siparia - Vessigny', region: 'trinidad', administrative_region: 'Siparia' },
  { value: 'vistabella', label: 'San Fernando - Vistabella', region: 'trinidad', administrative_region: 'San Fernando' },
  { value: 'waterloo', label: 'Couva–Tabaquite–Talparo - Waterloo', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'westmoorings', label: 'Diego Martin - Westmoorings', region: 'trinidad', administrative_region: 'Diego Martin' },
  { value: 'whiteland', label: 'Couva–Tabaquite–Talparo - Whiteland', region: 'trinidad', administrative_region: 'Couva–Tabaquite–Talparo' },
  { value: 'williamsville', label: 'Princes Town - Williamsville', region: 'trinidad', administrative_region: 'Princes Town' },
  { value: 'woodbrook', label: 'Port of Spain - Woodbrook', region: 'trinidad', administrative_region: 'Port of Spain' },

  // Tobago locations
  { value: 'arnos_vale', label: 'Tobago - Arnos Vale', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'auchenskeoch', label: 'Tobago - Auchenskeoch', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'bacolet', label: 'Tobago - Bacolet', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'bethel', label: 'Tobago - Bethel', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'belle_garden', label: 'Tobago - Belle Garden', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'black_rock', label: 'Tobago - Black Rock', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'bon_accord', label: 'Tobago - Bon Accord', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'buccoo', label: 'Tobago - Buccoo', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'calder_hall', label: 'Tobago - Calder Hall', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'canaan_tobago', label: 'Tobago - Canaan', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'carnbee', label: 'Tobago - Carnbee', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'castara', label: 'Tobago - Castara', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'charlotteville', label: 'Tobago - Charlotteville', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'culloden', label: 'Tobago - Culloden', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'delaford', label: 'Tobago - Delaford', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'glamorgan', label: 'Tobago - Glamorgan', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'goodwood', label: 'Tobago - Goodwood', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'hope', label: 'Tobago - Hope', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'john_dial', label: 'Tobago - John Dial', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'lanse_fourmi', label: 'Tobago - L\'Anse Fourmi', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'lambeau', label: 'Tobago - Lambeau', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'les_coteaux', label: 'Tobago - Les Coteaux', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'louis_dor', label: 'Tobago - Louis D\'Or', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'lowlands', label: 'Tobago - Lowlands', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'mason_hall', label: 'Tobago - Mason Hall', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'moriah', label: 'Tobago - Moriah', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'morne_quinton', label: 'Tobago - Morne Quinton', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'mount_saint_george', label: 'Tobago - Mount Saint George', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'orange_hill', label: 'Tobago - Orange Hill', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'pembroke', label: 'Tobago - Pembroke', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'plymouth', label: 'Tobago - Plymouth', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'rockly_vale', label: 'Tobago - Rockly Vale', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'roxborough', label: 'Tobago - Roxborough', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'scarborough', label: 'Tobago - Scarborough', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'signal_hill', label: 'Tobago - Signal Hill', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'speyside', label: 'Tobago - Speyside', region: 'tobago', administrative_region: 'Tobago' },
  { value: 'studley_park', label: 'Tobago - Studley Park', region: 'tobago', administrative_region: 'Tobago' }
];

export const getLocationsByRegion = () => {
  const trinidad = TRINIDAD_TOBAGO_LOCATIONS.filter(location => location.region === 'trinidad');
  const tobago = TRINIDAD_TOBAGO_LOCATIONS.filter(location => location.region === 'tobago');
  
  return { trinidad, tobago };
};

export const getAllLocations = () => TRINIDAD_TOBAGO_LOCATIONS;
