import html2canvas from 'html2canvas';
import { MedicationWithAdministrations } from '@/services/medicationService';

/**
 * Generate formatted plain text for all medications
 */
export function generateMedicationText(
  medications: MedicationWithAdministrations[],
  carePlanTitle?: string
): string {
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-US', { 
    weekday: 'long', 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });
  const timeStr = now.toLocaleTimeString('en-US', { 
    hour: '2-digit', 
    minute: '2-digit' 
  });

  let text = `📋 MEDICATION LIST\n`;
  if (carePlanTitle) {
    text += `Patient: ${carePlanTitle}\n`;
  }
  text += `Generated: ${dateStr} at ${timeStr}\n`;
  text += `\n━━━━━━━━━━━━━━━━━━━━\n\n`;

  if (medications.length === 0) {
    text += `No medications recorded.\n`;
  } else {
    medications.forEach((med, index) => {
      text += `💊 ${med.name}\n`;
      if (med.medication_type) {
        text += `   Type: ${med.medication_type}\n`;
      }
      if (med.dosage) {
        text += `   Dosage: ${med.dosage}\n`;
      }
      if (med.instructions) {
        text += `   Instructions: ${med.instructions}\n`;
      }
      if (med.special_instructions) {
        text += `   Special: ${med.special_instructions}\n`;
      }
      if (med.adherence_rate !== undefined) {
        text += `   Adherence: ${med.adherence_rate}%\n`;
      }
      if (index < medications.length - 1) {
        text += `\n`;
      }
    });
  }

  text += `\n━━━━━━━━━━━━━━━━━━━━\n`;
  text += `Generated by Tavara.care`;

  return text;
}

/**
 * Generate and download a JPG image of the medication card
 */
export async function downloadMedicationCardImage(
  elementId: string,
  filename: string = 'medication-card'
): Promise<boolean> {
  const element = document.getElementById(elementId);
  if (!element) {
    console.error('Element not found for screenshot:', elementId);
    return false;
  }

  try {
    // Make element visible temporarily for capture
    const originalDisplay = element.style.display;
    const originalPosition = element.style.position;
    const originalLeft = element.style.left;
    
    element.style.display = 'block';
    element.style.position = 'absolute';
    element.style.left = '-9999px';

    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      backgroundColor: '#ffffff',
      logging: false,
    });

    // Restore element visibility
    element.style.display = originalDisplay;
    element.style.position = originalPosition;
    element.style.left = originalLeft;

    // Convert to JPG and download
    const dataUrl = canvas.toDataURL('image/jpeg', 0.95);
    const link = document.createElement('a');
    link.download = `${filename}.jpg`;
    link.href = dataUrl;
    link.click();

    return true;
  } catch (error) {
    console.error('Error generating medication card image:', error);
    return false;
  }
}

/**
 * Copy medication text to clipboard
 */
export async function copyMedicationText(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (error) {
    console.error('Error copying to clipboard:', error);
    // Fallback for older browsers
    try {
      const textArea = document.createElement('textarea');
      textArea.value = text;
      textArea.style.position = 'fixed';
      textArea.style.left = '-9999px';
      document.body.appendChild(textArea);
      textArea.select();
      document.execCommand('copy');
      document.body.removeChild(textArea);
      return true;
    } catch (fallbackError) {
      console.error('Fallback copy failed:', fallbackError);
      return false;
    }
  }
}
