
import React from "react";

export interface OnboardingSectionLink {
  label: string;
  url: string;
}

export interface OnboardingSectionDef {
  id: string;
  title: string;
  iconName: string;
  description: string;
  items: string[];
  showFamilyData?: boolean;
  showProfessionalData?: boolean;
  links?: Record<number, string>;
  dateFields?: Record<number, string>;
  helperText?: string;
  serviceCategory?: string; // maps to billable_service_items.category for this section
}

export const ONBOARDING_SECTION_DEFS: OnboardingSectionDef[] = [
  {
    id: "medication_confirmation",
    title: "Medication Confirmation",
    iconName: "Pill",
    description: "Review and confirm all medications, dosages, and instructions for the care recipient",
    items: [
      "Review all medications listed below — verify names, dosages, and schedules are correct",
      "Confirm any special instructions (take with food, before bed, etc.)",
      "Report any missing medications or changes to your care coordinator",
    ],
    showFamilyData: true,
  },
  {
    id: "emergency_contacts",
    title: "Emergency Contact Verification",
    iconName: "Users",
    description: "Verify emergency contact details are accurate and up to date",
    items: [
      "Confirm emergency contact name and relationship are correct",
      "Verify emergency contact phone number is current and reachable",
      "Confirm primary contact details are accurate",
      "Report any changes to your care coordinator immediately",
    ],
    showFamilyData: true,
  },
  {
    id: "pre_call",
    title: "Pre-Call Preparation",
    iconName: "ClipboardCheck",
    description: "Admin review tasks before the onboarding call — included in your Care Assessment & Setup",
    helperText: "Care Assessment & Setup — Includes case review, care planning preparation, and onboarding coordination.",
    serviceCategory: "setup",
    items: [
      "Review family account status (registered, profile complete?)",
      "Review existing care plan (if family already created one) OR note: care plan to be created during/after call",
      "Note care recipient name, relationship, and primary conditions",
      "Have family's phone number / WhatsApp ready",
      "Review any notes from initial inquiry or chat registration data",
      "Prepare screen-share or walkthrough materials",
    ],
  },
  {
    id: "review_submissions",
    title: "Review Client Submissions",
    iconName: "Heart",
    description: "Review what the family already submitted — registration, care assessment, and legacy story",
    helperText: "More complex care situations — such as multiple conditions, dementia, behavioral support, or multi-household needs — may require additional planning and coordination.",
    showFamilyData: true,
    items: [
      "Review registration: care recipient name, relationship, care types, special needs",
      "Review care assessment: ADLs, conditions, care location",
      "Review legacy story: personality, hobbies, daily routine, joyful things",
      "Discuss what prompted them to seek care",
      "Confirm family's expectations and care goals",
      "Note any updates to cultural, dietary, or language preferences",
      "Confirm emergency contacts and physician information",
      "Note any edits needed for follow-up",
    ],
  },
  {
    id: "platform_overview",
    title: "Guided Platform Activation",
    iconName: "Monitor",
    description: "Your plan includes guided onboarding so your family knows exactly how to use Tavara with confidence",
    helperText: "Guided activation is included in your care coordination plan — no additional cost.",
    items: [
      "How to log in (email + password or magic link)",
      "Family dashboard layout and shortcuts",
      "Care Plans quick link on dashboard",
      "How to view their care plan details",
      "Care team members and assigned professionals",
      "How to access the medication dashboard",
      "How to access the meal planner",
    ],
  },
  {
    id: "care_plan",
    title: "Care Plan Review & Setup",
    iconName: "FileText",
    description: "Collaboratively review and finalize the care plan with the family",
    helperText: "Care plan setup is included in your coordination plan. Changes to care scope, schedules, or complexity may require a care plan adjustment.",
    serviceCategory: "core_plan",
    items: [
      "Review existing care plan details (if already created by family)",
      "Care plan types (Scheduled Care, On-Demand)",
      "Discuss and confirm weekday coverage: 8am-4pm / 8am-6pm / 6am-6pm / 6pm-8am / none",
      "Discuss and confirm weekend coverage: 6am-6pm / 8am-4pm / none",
      "Additional shifts if needed (evening/overnight options)",
      "How to view / edit care plan details",
      "Care team members tab — who's assigned",
      "Daily care logs tab — how family views completed logs",
    ],
  },
  {
    id: "medication",
    title: "Medication Management",
    iconName: "Pill",
    description: "Structured medication coordination, logging, and reporting for families and caregivers",
    helperText: "Medication coordination may be included or added depending on the care plan selected and care complexity.",
    serviceCategory: "weekly_addon",
    items: [
      "How family adds medications (name, dosage, frequency, schedule)",
      "Medication schedule view — today's medications at a glance",
      "How professionals administer and record medications",
      "Conflict-aware administration — prevents double-dosing",
      "Medication history and reports",
      "Export features (PDF / print)",
      "Printable medication cards for the caregiver",
    ],
  },
  {
    id: "meals",
    title: "Meal Management",
    iconName: "UtensilsCrossed",
    description: "Meal planning and nutrition features — basic meal support may be included in your care plan",
    helperText: "Basic daily dietary meal prep is included in standard care. More involved meal preparation or special dietary support may require a care adjustment.",
    serviceCategory: "weekly_addon",
    items: [
      "Meal planner — weekly meal scheduling",
      "Recipe library — browse and save recipes",
      "Grocery list manager — auto-generate from meal plan",
      "Nutrition tracker — monitor dietary intake",
      "How to share meal plans with the caregiver",
      "Meal preparation is the family's responsibility — caregiver performs light cooking of pre-prepared meals provided by the family",
    ],
  },
  {
    id: "care_environment",
    title: "Preparing Your Home for Care",
    iconName: "Leaf",
    description: "Support in preparing the home as a safe, dignified care environment — for your loved one's comfort and the caregiver's effectiveness",
    helperText: "Tavara helps the home become ready for care. This service supports comfort, dignity, safety, and caregiver sustainability — not cleaning or housekeeping.",
    serviceCategory: "care_environment_support",
    items: [
      "Home walkthrough and caregiver workflow mapping",
      "Hygiene, safety, and airflow assessment",
      "Decluttering recommendations and space optimization",
      "Caregiver workspace and movement considerations",
      "Light organization and sanitation planning guidance",
      "Coordination of deeper resets when needed (vendor management)",
    ],
  },
  {
    id: "daily_checklist",
    title: "Daily Care Checklist (Caregiver SOP)",
    iconName: "ListChecks",
    description: "Your care coordination plan helps ensure consistency, accountability, and clear daily care expectations",
    helperText: "Daily care documentation and SOP tracking are part of the managed care system. Selected monitoring and oversight items are billable service components when approved.",
    serviceCategory: "weekly_addon",
    items: [
      "How the professional fills out the checklist each shift",
      "One log per professional per care plan per day rule",
      "How family sees the completed daily logs",
      "Time-in / time-out tracking",
      "Shift notes and incident reporting",
      "Caregivers are assigned to the primary client — support to other household members is limited to approved, scoped services only",
      "Daily Care SOP + Monitoring — structured tracking, accountability, and care quality oversight (billable add-on)",
      "Daily Care SOP — One-Time Activation — $199 for 30-day full caregiver log access (alternative to weekly add-on)",
      "Secondary Household Support — additional structured support for secondary household members (billable add-on, requires scope agreement)",
      "Escalation support — coordination triggered by falls, urgent changes, or emergency response (billed per incident when triggered)",
    ],
  },
  {
    id: "professional_dashboard",
    title: "Professional Dashboard Overview",
    iconName: "LayoutDashboard",
    description: "Tavara supports your care team through structure, communication, and documentation tools",
    helperText: "Professional dashboard access and care team tools are included in your coordination plan.",
    items: [
      "Care assignments and client details",
      "Calendar view with daily log entries",
      "Medication dashboard for assigned care plans",
      "Document management and training modules",
      "Nurse Handbook & SOP resources (always accessible)",
    ],
  },
  {
    id: "caregiver_matching",
    title: "Caregiver Matching & Introduction",
    iconName: "Users",
    description: "Match the right caregiver and build your coordinated care team",
    helperText: "Each family's managed care setup includes: 1 primary caregiver, 1 backup caregiver, and 1 additional backup. Replacements within this coordinated pool are included. Replacements outside the pool may incur additional matching fees.",
    serviceCategory: "setup",
    items: [
      "Discuss caregiver preferences (skills, personality, language)",
      "Explain matching process and timeline",
      "Planned care team pool: 1 primary + 1 backup + 1 additional backup caregiver",
      "Replacements within the coordinated pool are included in your plan",
      "Replacements beyond the planned pool may incur additional caregiver matching / emergency replacement charges",
      "Offer trial day option vs immediate start",
      "Tentatively assign caregiver (confirm after call)",
      "Arrange meet-and-greet if applicable",
    ],
  },
  {
    id: "rates_and_changes",
    title: "Rates, Care Changes & Escalation",
    iconName: "DollarSign",
    description: "Pricing transparency, holiday/overtime rates, and how costs evolve as care needs change",
    helperText: "Changes in scope, complexity, schedule, or service level may require a care adjustment and will always be discussed before taking effect. Optional one-time administrative support is available to coordinate NIS employer registration.",
    serviceCategory: "care_change",
    items: [
      "Review rate tiers: Standard ($40/hr) — GAPP-certified personal care, medication admin & logging, vitals monitoring, basic daily dietary meal prep, daily care documentation, specialized care (dementia, palliative, post-surgical)",
      "Full Service ($45/hr) — Everything in Standard + advanced specialist-directed meal prep (holidays & special occasions), complex medical needs (wound care, catheter care, oxygen management), overnight/live-in shifts, advanced certifications (RN, LPN), behavioral health support",
      "Premium ($50+/hr) — Everything in Full Service + change-in-care-plan management, disease progression support, multi-specialist coordination, 24/7 on-call availability, advanced palliative/end-of-life care, family training & transition planning",
      "Holiday rates apply — time and a half (1.5x) on recognized holidays; double time (2x) on Christmas",
      "Extended hours / overtime rates — time and a half for shifts beyond standard coverage",
      "Change orders: any increase in service scope is recorded and discussed before taking effect",
      "Care escalation triggers — bedridden status, wheelchair/lift needs, increased fall risk",
      "Dietary changes — stricter dietary requirements may increase care complexity and cost",
      "Medication changes — new prescriptions or regimen changes require updated care documentation",
      "Errands and personal runs (grocery, market) — arranged privately with nurse at agreed stipend, outside Tavara scope",
      "Baseline care level is established at onboarding; all changes from baseline are documented",
      "Family will be notified and consulted before any rate or care level adjustment takes effect",
      "NIS Employer Registration Support — $349 one-time optional administrative coordination to register the family as the employer for NIS purposes (forms, documents, authorizations, submission). NIS contributions themselves remain separate and are the family's responsibility.",
      "Tavara does not employ the caregiver — the family is the employer of record for NIS purposes. Tavara coordinates and supports the registration process. Of course, this is something you can absolutely handle on your own, but we're here to coordinate and support you through it — because it truly takes a village to care. We offer this as an option to make the process a bit lighter for you.",
    ],
  },
  {
    id: "next_steps",
    title: "Next Steps & Follow-Up",
    iconName: "CalendarCheck",
    description: "Your care coordination plan includes activation support and early follow-up to help ensure a smooth start",
    helperText: "Activation support and first-week check-in are included in your care coordination plan.",
    items: [
      "Confirm care start date (or trial day date)",
      "Set up WhatsApp care group",
      "Schedule 24-48 hour post-first-visit check-in",
      "Share admin/coordinator direct contact info",
      "Confirm family knows how to reach support",
      "Send welcome summary via email/WhatsApp after call",
    ],
  },
  {
    id: "communication",
    title: "Communication & Notifications",
    iconName: "MessageSquare",
    description: "Tavara keeps everyone connected through structured updates, communication, and care visibility",
    helperText: "Communication tools and care visibility are included in your coordination plan.",
    items: [
      "Care plan edit notifications (bidirectional)",
      "Daily log visibility for family",
      "WhatsApp care group updates",
      "How to contact the care coordinator",
      "Emergency contact setup and visibility",
    ],
  },
  {
    id: "family_terms",
    title: "Terms & Conditions of Engagement",
    iconName: "FileCheck",
    description: "Family acknowledges and agrees to the terms of engaging Tavara Care services",
    items: [
      "The family engages caregivers directly, with Tavara providing coordination, structure, and support",
      "Family understands their care team member is part of a coordinated rotation pool managed by Tavara for seamless coverage",
      "Family confirms they are subscribing to Active Care Management (weekly) — refer to quotation for full pricing details",
      "Family understands payment is due weekly (every Friday) as per the billing terms",
      "The family is responsible for statutory obligations including NIS (National Insurance) contributions. Tavara provides guidance and tools to help manage these requirements",
      "Family understands rate adjustments may apply if care needs change, with prior notice",
      "Family agrees to provide Wi-Fi access (if available) to the caregiver for platform use — medication logging, care documentation, and shift tracking",
      "Family confirms they have reviewed the quotation and accepted all terms (digital approval)",
      "Family understands that care is primarily provided for the identified care recipient and does not extend to other household members unless explicitly agreed and billed as an additional service",
      "Family confirms approval of any additional care services requested (e.g. podiatric care for secondary household member), as outlined in the quotation",
      "Family understands that approved secondary services are limited to the defined task only and do not extend to general caregiving for the secondary individual",
      "Family acknowledges that additional services are billed weekly and will continue unless discontinued in writing with one (1) week's notice",
      "Family confirms that caregiver support will be provided in a manner that respects existing household roles and routines, with the caregiver supporting — not replacing — family responsibilities where appropriate",
    ],
  },
  {
    id: "post_onboarding",
    title: "Post-Onboarding Summary",
    iconName: "CheckCircle2",
    description: "Summary of completed onboarding, approved services, and next steps for the family",
    helperText: "Review the billing & care structure summary below to confirm all approved services before commencement.",
    items: [
      "Onboarding completed successfully — welcome to Tavara.Care!",
      "Care team member confirmed and to be introduced to family",
      "First meeting: Tavara coordinator, care team member, and family at client residence",
      "Care team member commences work at client residence (start date confirms billing period)",
      "Care team member compensation coordinated weekly by Tavara",
      "Tavara subscription: Active Care Management (weekly)",
      "NIS contributions are the family's responsibility — Tavara provides tools and guidance to manage them",
      "View your care plan and team",
      "View your onboarding progress",
      "Generate your first quote",
      "Generate your first invoice",
      "Generate your first receipt",
    ],
    links: {
      5: "/subscription",
      7: "/family/care-management",
      8: "/family/onboarding-checklist",
      9: "/family/care-management?tab=documents",
      10: "/family/care-management?tab=documents",
      11: "/family/care-management?tab=documents",
    },
    dateFields: {
      1: "Introduction Date",
      2: "Meeting Date & Time",
      3: "Start Date",
    },
  },
];

export function getTotalItems(): number {
  return ONBOARDING_SECTION_DEFS.reduce((sum, s) => sum + s.items.length, 0);
}
