
import { OnboardingSectionDef } from "./onboardingSections";

export const PROFESSIONAL_ONBOARDING_SECTION_DEFS: OnboardingSectionDef[] = [
  {
    id: "pre_screening",
    title: "Pre-Screening Review",
    iconName: "ClipboardCheck",
    description: "Review background check, references, and screening session status",
    showProfessionalData: true,
    items: [
      "Review professional's registration data (name, experience, certifications)",
      "Check background check status and proof document",
      "Review submitted references (minimum 2 required)",
      "Confirm screening session outcome (head nurse interview)",
      "Verify ID and legal authorization to work",
      "Review any notes from initial inquiry or chat registration",
    ],
  },
  {
    id: "document_verification",
    title: "Document Verification",
    iconName: "FileText",
    description: "Certifications, ID, insurance, and training certificates",
    items: [
      "Valid government-issued ID uploaded and verified",
      "Professional certifications (CNA, LPN, RN, etc.) verified",
      "Background check proof document on file",
      "First aid / CPR certification current",
      "Insurance or bonding documentation (if applicable)",
      "Training certificates reviewed and filed",
    ],
  },
  {
    id: "platform_walkthrough",
    title: "Platform Walkthrough",
    iconName: "Monitor",
    description: "Login, professional dashboard, assignments, and schedule",
    items: [
      "How to log in (email + password or magic link)",
      "Professional dashboard layout and shortcuts",
      "How to view assigned families and care plans",
      "Calendar view and schedule management",
      "How to access the daily care checklist",
      "Profile hub — updating availability, certifications, and documents",
      "Message board and communication tools",
    ],
  },
  {
    id: "care_plan_training",
    title: "Care Plan & Assignment Training",
    iconName: "Heart",
    description: "How assignments work, care plan details, and care team coordination",
    items: [
      "How caregiver assignments are created (automatic vs admin-assigned)",
      "Understanding care plan details — schedule, tasks, special needs",
      "Care team members — who else is on the team",
      "How to view family profile and care recipient information",
      "Trial day process vs immediate start",
      "What to do if there's a scheduling conflict",
    ],
  },
  {
    id: "daily_checklist_sop",
    title: "Daily Checklist SOP",
    iconName: "ListChecks",
    description: "Shift check-in/out, daily log, medication admin, and incident reports",
    items: [
      "How to fill out the daily care checklist each shift",
      "One log per professional per care plan per day rule",
      "Time-in / time-out tracking requirements",
      "Shift notes and incident reporting procedures",
      "How the family sees completed daily logs",
      "Escalation protocol for urgent situations",
      "Caregivers are assigned to the primary client — support to other household members is limited to approved, scoped services only",
    ],
  },
  {
    id: "medication_meal_protocols",
    title: "Medication & Meal Protocols",
    iconName: "Pill",
    description: "Medication dashboard, meal plan access, and dietary requirements",
    items: [
      "How to access the medication dashboard for assigned care plans",
      "Administering and recording medications (conflict-aware system)",
      "Medication history and double-dosing prevention",
      "Printable medication cards for quick reference",
      "Meal plan access — caregiver performs light cooking of pre-prepared meals; family is responsible for meal prep and ingredients",
      "Handling dietary restrictions and allergies",
    ],
  },
  {
    id: "rates_payment",
    title: "Rates, Payment & Policies",
    iconName: "DollarSign",
    description: "Rate tiers, holiday/overtime rates, payment schedule, and change orders",
    items: [
      "Review rate tiers: Standard ($35/hr) — GAPP-certified personal care, medication admin & logging, vitals monitoring, basic daily dietary meal prep, daily care documentation, specialized care (dementia, palliative, post-surgical)",
      "Full Service ($40/hr) — Everything in Standard + advanced specialist-directed meal prep (holidays & special occasions), complex medical needs (wound care, catheter care, oxygen management), overnight/live-in shifts, advanced certifications (RN, LPN), behavioral health support",
      "Premium ($45+/hr) — Everything in Full Service + change-in-care-plan management, disease progression support, multi-specialist coordination, 24/7 on-call availability, advanced palliative/end-of-life care, family training & transition planning",
      "Holiday rates — time and a half (1.5x); double time (2x) on Christmas",
      "Extended hours / overtime rates — time and a half beyond standard shifts",
      "Payment schedule and method (weekly/bi-weekly)",
      "Change orders — how care scope increases affect compensation",
      "Attendance and punctuality expectations",
      "Cancellation and no-show policy",
    ],
  },
  {
    id: "communication_support",
    title: "Communication & Support",
    iconName: "MessageSquare",
    description: "WhatsApp groups, coordinator contact, and escalation procedures",
    items: [
      "Your Tavara Care Dashboard is your central hub — assignments, daily logs, medications, documents, and messages all in one place",
      "WhatsApp care group setup — how communication flows alongside your dashboard",
      "How to contact the care coordinator directly (via dashboard or WhatsApp)",
      "Emergency escalation procedures",
      "Professional message board for peer support",
      "Nurse Handbook & SOP resources — always accessible from your dashboard",
      "How to report concerns or request support through the platform",
    ],
  },
  {
    id: "next_steps_assignment",
    title: "Next Steps & First Assignment",
    iconName: "CalendarCheck",
    description: "Confirm availability, first assignment prep, and 48hr check-in",
    items: [
      "Confirm availability and preferred schedule",
      "Review first assignment details (family, care plan, start date)",
      "Meet-and-greet with family (if applicable)",
      "Ensure all required documents are uploaded",
      "Schedule 48-hour post-first-shift check-in",
      "Share coordinator direct contact info and welcome packet",
    ],
  },
  {
    id: "terms_conditions",
    title: "Terms & Conditions of Engagement",
    iconName: "FileText",
    description: "Critical employment terms the professional must acknowledge and accept",
    items: [
      "Professional acknowledges they are hired through Tavara Care, not directly by the family",
      "Professional understands they are part of a caregiver rotation pool for seamless coverage",
      "Professional agrees to a 30-day probationary/orientation period",
      "Professional confirms payment is made weekly by Tavara (every Friday)",
      "Professional understands payment processing may take up to 3 business days",
      "Professional acknowledges NIS contributions are handled by Tavara as the employer of record",
      "Professional agrees to Tavara's attendance, punctuality, and cancellation policies",
      "Professional confirms they have reviewed and accepted all terms (digital approval)",
    ],
  },
  {
    id: "post_onboarding",
    title: "Post-Onboarding Summary",
    iconName: "CheckCircle2",
    description: "Final milestones, assignment confirmation, and next steps",
    items: [
      "Onboarding completed successfully — welcome to the Tavara Care team",
      "Assigned nurse confirmed and to be introduced to family",
      "First meeting: Tavara coordinator, professional, and family at client residence",
      "Professional commences work at client residence",
      "Professional is paid weekly by Tavara (every Friday)",
      "NIS contributions handled by Tavara as employer of record",
      "View your assignments and care plans",
      "View your onboarding progress",
    ],
    dateFields: {
      1: "Introduction Date",
      2: "Meeting Date",
      3: "Start Date",
    },
    links: {
      6: "/dashboard/professional",
      7: "/professional/onboarding-checklist",
    },
  },
];

export function getProfessionalTotalItems(): number {
  return PROFESSIONAL_ONBOARDING_SECTION_DEFS.reduce((sum, s) => sum + s.items.length, 0);
}
