
INSERT INTO nudge_templates (name, stage, role, message_type, message_template) VALUES
('Family Legacy Story', 'step_5', 'family', 'whatsapp', E'Hi [Name]! 💙 Chan from Tavara Care.\n\nYou''re [X]% through your care journey — great progress! One important step remaining is your loved one''s Legacy Story.\n\nThis helps your caregiver understand who your loved one truly is — their favorite meals, music, routines, and what brings them joy. It makes such a difference in the quality of care they receive.\n\n📖 Complete it here: https://tavaracare.lovable.app/family/story\n\nIt only takes a few minutes and your caregiver will thank you for it!\n- Chan, Tavara Care 💙'),

('Family Matched - Schedule Care', 'step_6', 'family', 'whatsapp', E'Hi [Name]! 🎉 Chan from Tavara Care.\n\nGreat news — you''ve been matched with a professional caregiver! Your care team is taking shape.\n\nYour next step is to schedule a care visit so we can get started. You can:\n✅ Schedule a one-time care session\n✅ Book a home site visit with our team\n\n📅 Visit your dashboard: https://tavaracare.lovable.app/dashboard/family\n\nWe''re excited to get your family the support they deserve!\n- Chan, Tavara Care 💙'),

('Family Visit Scheduling', 'step_7', 'family', 'whatsapp', E'Hi [Name]! 👋 Chan from Tavara Care.\n\nJust checking in — have you had a chance to schedule your home site visit yet? This is where our team visits your home to finalize the care plan and ensure everything is set up perfectly.\n\n📅 Schedule here: https://tavaracare.lovable.app/family/visit-scheduling\n\nIt''s a quick and easy process. We''re here to help every step of the way!\n- Chan, Tavara Care 💙'),

('Family Budget Update', 'budget_update', 'family', 'whatsapp', E'Hi [Name]! 💙 Chan from Tavara Care.\n\nWe''ve updated our care rate options to better reflect the professional standards of certified caregivers in Trinidad & Tobago:\n\n💰 $35/hr — Standard: Companionship, medication reminders, light meal prep\n⭐ $40/hr — Full Service (Recommended): GAPP-certified care including meals, light cleaning, personal care\n👑 $45+/hr — Premium: Specialized or complex medical care\n\nPlease take a moment to update your budget preferences in your profile to ensure we match you with the right level of care.\n\n🔗 Update here: https://tavaracare.lovable.app/dashboard/family\n- Chan, Tavara Care 💙'),

('Family Re-engagement', 're_engagement', 'family', 'whatsapp', E'Hi [Name]! 👋 Chan from Tavara Care.\n\nWe noticed it''s been a little while since you visited Tavara. Your care journey is [X]% complete — you''re so close!\n\nOur caregivers are ready and waiting to support your family. Let''s pick up where you left off.\n\n🔗 Continue here: https://tavaracare.lovable.app/dashboard/family\n\nNeed help? Just reply to this message and we''ll guide you through it!\n- Chan, Tavara Care 💙');
