
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables instead of hardcoded values
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Fallback only for local development without env variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn('Supabase credentials not found in environment variables!');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);

// Add a helper function to identify the current environment
export const getCurrentEnvironment = (): 'development' | 'preview' | 'production' => {
  return import.meta.env.VITE_ENV as 'development' | 'preview' | 'production' || 'development';
};

// Log the active environment (helpful for debugging)
console.log(`Active environment: ${getCurrentEnvironment()}`);
